"""Supplementary evidence for the visual course revision."""
from reportlab.lib.units import mm
from production.course_evidence import *

def write_visual_appendix(a):
    def table(rows,caption,widths):a.table(rows,caption,[166*mm*w/sum(widths) for w in widths])
    a.page();a.h('A11 Training-only feature-redundancy sensitivity')
    a.p('A fixed protocol screened feature overlap using only the 17 training participants in each rotation. We calculated pooled Spearman correlations and the median signed correlation calculated separately within participants. A feature was removed only when an already retained feature had absolute correlation at least 0.90 on both measures, with matching signs. This rule required strong overlap both across training trials and within a typical participant. It does not establish that the retained features are independent.')
    a.p('The priority order favored initiation time, movement time, peak speed, relative time to peak, path length, curvature index, lateral deviation and speed-peak count, followed by endpoint x, straight-line distance and endpoint y. This order and threshold were recorded before computing the sensitivity results. Every rotation retained the same nine features, dropping straight-line distance and endpoint y in favor of path length.')
    table([['Removed feature','Pooled rho range','Median within-person rho'],['Straight-line distance','0.933-0.971','0.953-0.978'],['Endpoint y','0.934-0.969','0.956-0.982']],'<b>Table A10.</b> Training correlations with path length across four rotations. All values are positive. High correlation reflects overlap in this dataset, rather than a universal equivalence of these quantities.',[2,1.5,1.5])
    a.p('The frozen models generated the same 120 movements per test participant and seed as before. No neural model was retrained. The original eleven-feature scores reproduced to a maximum absolute difference of 4.44 x 10<super>-16</super>. For the nine-feature view, training data defined the restricted feature scales and a new training-derived kernel bandwidth. We recomputed mean KS, energy and MMD for both views, averaging neural seeds within participant.')
    results=pd.read_csv(OUT/'feature_redundancy_2026_09_14/summary.csv')
    rows=[['Model','n','Mean KS','Energy','MMD squared']]
    for n in (3,8):
        for f in FAMILIES:
            r=results[(results.model_family==f)&(results.latent_dim==n)&(results.feature_view=='reduced')].iloc[0]
            rows.append([LABELS[f],n,*[f'{r[m]:.4f}' for m in ('mean_ks','energy_distance','mmd_rbf')]])
    table(rows,'<b>Table A11.</b> Nine-feature discrepancies. Lower is better within this representation. Values cannot be used to claim absolute improvement over eleven features because removing coordinates changes the endpoint.',[1.7,.4,1,1,1])
    a.p('The complete sensitivity family contained 72 tests: six compact-model pairs x two capacities x three metrics x two feature views. BH and Holm each corrected all 72 together. Both VAE and CVAE beat spline on every reduced-feature metric at both capacities under both corrections (largest Holm p = 0.00332). At n = 8, VAE versus CVAE had reduced-feature BH q = 0.149 for KS, 0.289 for energy and 0.428 for MMD. None was significant. The variational advantage over spline persisted; a unique VAE advantage did not.')
    a.p('The primary eleven-feature results and their historical 140-test correction remain unchanged. The separate sensitivity family must not be substituted for that correction. Removing correlated coordinates does not automatically reduce the number of model comparisons, and neither analysis consists of eleven feature-level KS p-values. Source: production/feature_redundancy_2026_09_14/; scripts/analyze_feature_redundancy.py.')
    a.page();a.h('A12 Reconstruction in spatial and phase coordinates')
    a.p('An x-y overlay displays spatial shape but can conceal differences in progression along the same path. The coordinate-versus-phase panels show the same recorded trial and the spline and VAE reconstructions at both capacities. Reconstruction MSE compares coordinates at corresponding phases, so these differences also contribute to its value.')
    a.figure(OUT/'course_assets/reconstruction_phase.png','<b>Figure A1.</b> Subject01 median-duration trial, selected before inspecting errors. Black: recorded coordinates. Color identifies the model; dashed lines indicate n = 3 and solid lines n = 8. Phase is relative elapsed time in the modeled interval. Both panels retain coordinate units. The illustrative neural fit uses fold 2, seed 42.',90*mm)
    a.figure(OUT/'course_assets/reconstruction_examples.png','<b>Figure A2.</b> The same trial in x-y coordinates for all four models. Black: recorded; dashed: reconstruction. Equal x/y scale and shared limits retain physical proportions. An apparently close spatial overlay can still differ in the phase at which a position is reached.',115*mm)
    for n in (3,8):
        a.page();a.h(f'A13 Recorded and generated feature distributions: n = {n}')
        a.p('These empirical cumulative curves show all eleven features for the same identifier-selected participant. The recorded query set contains 90 trials and each model generates 120. Each feature curve is a marginal distribution; the joint energy and MMD scores also use dependence across features. The panels illustrate model behavior and do not replace the cohort-level paired tests.')
        a.figure(OUT/f'course_assets/features_all_n{n}.png',f'<b>Figure A{3 if n==3 else 4}.</b> Subject01, n = {n}, fold 2, neural seed 42. The fraction of values at or below each horizontal-axis value is shown vertically. Smaller maximum vertical separation from the black recorded curve means smaller KS for that feature and participant. All plotted values are included; feature axes have their own physical scales.',199*mm)
        a.p('Straight-line distance and endpoint y are retained here to document the original eleven-feature analysis. The training-only reduction in A11 omits them from a separate sensitivity endpoint. Their removal was based on training correlation and a recorded feature priority, not on which query curves looked least favorable.','caption')
